### PR TITLE
Add Turkish Translation

### PR DESCRIPTION
**Pull request by aliyasiny65**
Hello,

I added Turkish language support via POEditor.

### CODE REVIEW

**Comment by nkming2** [comment]
Hi, thanks for your contribution! :+1: I'll test it out and if everything's good, merge and enable it in the coming release. Thanks again!

**Comment by aliyasiny65** [comment]
Hello, is there any progress?

**Comment by aliyasiny65** [comment]
> Hi, thanks for your contribution! :+1: I'll test it out and if everything's good, merge and enable it in the coming release. Thanks again!

Hello.

**Comment by nkming2** [comment]
Merged, sorry for the delay. And thanks again!

**Pull request merged**
